server:
  address:     ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

logger:
  level : "all"
  stdout: true

# Database.
database:
  default:
    link:   "mysql:root:123456@tcp(127.0.0.1:3306)/gf_db_demo?loc=Local"
    debug:  true
    charset: "utf8mb4" # 数据库编码
    dryRun: false # 空跑
    maxIdle: 10 # 连接池最大闲置的连接数
    maxOpen: 10 # 连接池最大打开的连接数
    maxLifetime: 30 # (单位秒)连接对象可重复使用的时间长度
# 数据库日志
  logger:
    level:   "all"
    stdout:  true
    Path: "resource/log/sql"

# Redis 配置示例
redis:
  default:
    address: 127.0.0.1:6379
    db: 1
    pass:
    idleTimeout: 600

# 七牛云
qiniu:
  bucket: "gf-test-bucket"
  accessKey: "CTFY_7bnK-XZkFK8P7RGSoQYBMcMB2eE4cfO-OAx"
  secretKey: "6P2FEBD24B5l6XR-VVm3kBOi5RBJ1sL-q8nPgNsN"
  url: "http://vms-file.canyonwan.top/"

upload:
  path: "upload_temp"