// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "gf_playground/internal/logic/account"
	_ "gf_playground/internal/logic/banner"
	_ "gf_playground/internal/logic/bizctx"
	_ "gf_playground/internal/logic/data_statistics"
	_ "gf_playground/internal/logic/position"
	_ "gf_playground/internal/logic/session"
	_ "gf_playground/internal/logic/todo"
)
