// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// AccountInfo is the golang structure of table account_info for DAO operations like Where/Data.
type AccountInfo struct {
	g.Meta       `orm:"table:account_info, do:true"`
	Id           interface{} // id
	Account      interface{} // 帐号
	Password     interface{} // 密码
	IsSuperAdmin interface{} // 是否是超级管理员
	RoleIds      interface{} // 角色Ids
	UserSalt     interface{} // 加密盐
	CreatedAt    *gtime.Time // 创建时间
	UpdatedAt    *gtime.Time // 更新时间
	DeletedAt    *gtime.Time // 删除时间
}
