// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Banner is the golang structure of table banner for DAO operations like Where/Data.
type Banner struct {
	g.Meta  `orm:"table:banner, do:true"`
	Id      interface{} //
	Url     interface{} //
	JumpUrl interface{} //
	Sort    interface{} //
}
