// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Banner is the golang structure of table banner for DAO operations like Where/Data.
type Banner struct {
	g.Meta    `orm:"table:banner, do:true"`
	Id        interface{} // 主键ID
	Url       interface{} // 轮播图地址
	JumpLink  interface{} // 跳转地址
	Sort      interface{} // 轮播图的排序
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
