// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// FileInfo is the golang structure of table file_info for DAO operations like Where/Data.
type FileInfo struct {
	g.Meta       `orm:"table:file_info, do:true"`
	Id           interface{} //
	FileUrl      interface{} // 文件地址
	FileName     interface{} // 文件名称
	FileType     interface{} // 文件类型
	FileTypeName interface{} // 文件类型名称
	FileSize     interface{} // 文件大小
	UserId       interface{} // 用户id
	CreatedAt    *gtime.Time //
	UpdatedAt    *gtime.Time //
}
