// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// PositionInfo is the golang structure of table position_info for DAO operations like Where/Data.
type PositionInfo struct {
	g.Meta       `orm:"table:position_info, do:true"`
	Id           interface{} //
	GoodsName    interface{} // 商品名称
	GoodsPicture interface{} // 商品主图
	GoodsId      interface{} //
	LinkUrl      interface{} // 跳转地址
	Sort         interface{} //
	CreatedAt    *gtime.Time //
	UpdateedAt   *gtime.Time //
	DeletedAt    *gtime.Time //
}
