// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Todo is the golang structure of table todo for DAO operations like Where/Data.
type Todo struct {
	g.Meta    `orm:"table:todo, do:true"`
	Id        interface{} // id
	Title     interface{} // 标题
	Content   interface{} // 详细内容
	CreatedAt *gtime.Time // 创建时间
	UpdatedAt *gtime.Time // 更新时间
	DeletedAt *gtime.Time // 删除时间
}
