// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// DataStatisticsDao is the data access object for table data_statistics.go.
type DataStatisticsDao struct {
	table   string                // table is the underlying table name of the DAO.
	group   string                // group is the database configuration group name of current DAO.
	columns DataStatisticsColumns // columns contains all the column names of Table for convenient usage.
}

// DataStatisticsColumns defines and stores column names for table data_statistics.go.
type DataStatisticsColumns struct {
	Id               string // id
	TodayOrderCounts string // 今日订单总数
	DAU              string // 日活
	ConversionRate   string // 转化率
}

// dataStatisticsColumns holds the columns for table data_statistics.go.
var dataStatisticsColumns = DataStatisticsColumns{
	Id:               "id",
	TodayOrderCounts: "today_order_counts",
	DAU:              "DAU",
	ConversionRate:   "conversion_rate",
}

// NewDataStatisticsDao creates and returns a new DAO object for table data access.
func NewDataStatisticsDao() *DataStatisticsDao {
	return &DataStatisticsDao{
		group:   "default",
		table:   "data_statistics.go",
		columns: dataStatisticsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *DataStatisticsDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *DataStatisticsDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *DataStatisticsDao) Columns() DataStatisticsColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *DataStatisticsDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *DataStatisticsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *DataStatisticsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
