
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(127.0.0.1:3306)/gf_db_demo"
        jsonCase: "CamelLower"
        descriptionTag: true
        noModelComment: false
        overwriteDao: true
        stdTime: true
        gJsonSupport: true