// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/internal/model"
)

type (
	IBanner interface {
		Create(ctx context.Context, in model.BannerCreateInput) (out *model.BannerCreateOutput, err error)
		GetSingle(ctx context.Context, in model.BannerGetInput) (out *model.BannerGetOutput, err error)
	}
)

var (
	localBanner IBanner
)

func Banner() IBanner {
	if localBanner == nil {
		panic("implement not found for interface IBanner, forgot register?")
	}
	return localBanner
}

func RegisterBanner(i IBanner) {
	localBanner = i
}
