// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/internal/model"
)

type (
	IDataStatistics interface {
		DataStatistics(ctx context.Context) (out *model.DataStatisticsGetOutput, err error)
	}
)

var (
	localDataStatistics IDataStatistics
)

func DataStatistics() IDataStatistics {
	if localDataStatistics == nil {
		panic("implement not found for interface IDataStatistics, forgot register?")
	}
	return localDataStatistics
}

func RegisterDataStatistics(i IDataStatistics) {
	localDataStatistics = i
}
