// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/internal/model"
)

type (
	IPermission interface {
		Create(ctx context.Context, in model.PermissionCreateInput) (out *model.PermissionCreateOutput, err error)
		Update(ctx context.Context, in model.PermissionUpdateInput) (out *model.PermissionUpdateOutput, err error)
		Delete(ctx context.Context, id uint) (out *model.PermissionDeleteOutput, err error)
		Page(ctx context.Context, in model.PermissionPageInput) (out *model.PermissionPageOutput, err error)
		List(ctx context.Context, in model.PermissionListInput) (out *model.PermissionListOutput, err error)
	}
)

var (
	localPermission IPermission
)

func Permission() IPermission {
	if localPermission == nil {
		panic("implement not found for interface IPermission, forgot register?")
	}
	return localPermission
}

func RegisterPermission(i IPermission) {
	localPermission = i
}
