// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/internal/model"
	"gf_playground/internal/model/entity"
)

type (
	ISession interface {
		SetUser(ctx context.Context, user *entity.AccountInfo) error
		GetUser(ctx context.Context) *entity.AccountInfo
		RemoveUser(ctx context.Context) error
		SetNotice(ctx context.Context, message *model.SessionNotice) error
		GetNotice(ctx context.Context) (*model.SessionNotice, error)
		RemoveNotice(ctx context.Context) error
	}
)

var (
	localSession ISession
)

func Session() ISession {
	if localSession == nil {
		panic("implement not found for interface ISession, forgot register?")
	}
	return localSession
}

func RegisterSession(i ISession) {
	localSession = i
}
