// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/api/v1/common"
	"gf_playground/internal/model"
)

type (
	ITodo interface {
		GetList(ctx context.Context) (out *model.TodoListGetOutput, err error)
		GetPage(ctx context.Context, in model.TodoPageGetInput) (out *common.PageCommonRes, err error)
		Create(ctx context.Context, in *model.TodoCreateInput) (out *model.TodoCreateOutput, err error)
		Update(ctx context.Context, in model.TodoUpdateInput) (err error)
		Delete(ctx context.Context, id int) (err error)
	}
)

var (
	localTodo ITodo
)

func Todo() ITodo {
	if localTodo == nil {
		panic("implement not found for interface ITodo, forgot register?")
	}
	return localTodo
}

func RegisterTodo(i ITodo) {
	localTodo = i
}
