// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf_playground/internal/model"
)

type (
	ITodo interface {
		Get(ctx context.Context) (out model.TodoGetOutput, err error)
		Create(ctx context.Context, in model.TodoCreateInput) (out model.TodoCreateOutput, err error)
		Update(ctx context.Context, in model.TodoUpdateInput) (out model.TodoUpdateOutput, err error)
		Delete(ctx context.Context, in model.TodoDeleteInput) (err error)
	}
)

var (
	localTodo ITodo
)

func Todo() ITodo {
	if localTodo == nil {
		panic("implement not found for interface ITodo, forgot register?")
	}
	return localTodo
}

func RegisterTodo(i ITodo) {
	localTodo = i
}
