// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf_playground/internal/dao/internal"
)

// internalAccountInfoDao is internal type for wrapping internal DAO implements.
type internalAccountInfoDao = *internal.AccountInfoDao

// accountInfoDao is the data access object for table account_info.
// You can define custom methods on it to extend its functionality as you wish.
type accountInfoDao struct {
	internalAccountInfoDao
}

var (
	// AccountInfo is globally public accessible object for table account_info operations.
	AccountInfo = accountInfoDao{
		internal.NewAccountInfoDao(),
	}
)

// Fill with you ideas below.
