// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Banner is the golang structure for table banner.
type Banner struct {
	Id        int         `json:"id"        description:"主键ID"`   // 主键ID
	Url       string      `json:"url"       description:"轮播图地址"`  // 轮播图地址
	JumpLink  string      `json:"jumpLink"  description:"跳转地址"`   // 跳转地址
	Sort      int         `json:"sort"      description:"轮播图的排序"` // 轮播图的排序
	CreatedAt *gtime.Time `json:"createdAt" description:"创建时间"`   // 创建时间
	UpdatedAt *gtime.Time `json:"updatedAt" description:"更新时间"`   // 更新时间
	DeletedAt *gtime.Time `json:"deletedAt" description:"删除时间"`   // 删除时间
}
