// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Banner is the golang structure for table banner.
type Banner struct {
	Id      int    `json:"id"      description:""` //
	Url     string `json:"url"     description:""` //
	JumpUrl string `json:"jumpUrl" description:""` //
	Sort    int    `json:"sort"    description:""` //
}
