// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// FileInfo is the golang structure for table file_info.
type FileInfo struct {
	Id           int         `json:"id"           description:""`       //
	FileUrl      string      `json:"fileUrl"      description:"文件地址"`   // 文件地址
	FileName     string      `json:"fileName"     description:"文件名称"`   // 文件名称
	FileType     int         `json:"fileType"     description:"文件类型"`   // 文件类型
	FileTypeName string      `json:"fileTypeName" description:"文件类型名称"` // 文件类型名称
	FileSize     int         `json:"fileSize"     description:"文件大小"`   // 文件大小
	UserId       int         `json:"userId"       description:"用户id"`   // 用户id
	CreatedAt    *gtime.Time `json:"createdAt"    description:""`       //
	UpdatedAt    *gtime.Time `json:"updatedAt"    description:""`       //
}
