// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"time"
)

// Goods is the golang structure for table goods.
type Goods struct {
	Id          int       `json:"id"          description:"商品表id"` // 商品表id
	Name        string    `json:"name"        description:"商品名称"`  // 商品名称
	Description string    `json:"description" description:"商品描述"`  // 商品描述
	CreateAt    time.Time `json:"createAt"    description:""`      //
	UpdateAt    time.Time `json:"updateAt"    description:""`      //
}
